global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "battleplanes-backend"
    metrics_path: "/metrics/"
    static_configs:
      - targets: ["backend-blue:8000", "backend-green:8000"]
